### ISSUE TITLE
Pull and Build initial App Code 

### ISSUE THREAD

**Issue by n-critser** [WhiteWhaleXYZ/WhiteWhale#13]
1st iteration of the app code is now up in the Dev branch. Please pull and build.

**Comment by Bjornkjohnson** [comment]
From Nicks Email

Hey all,
I've pushed the first batch of files to github. The Dev branch only for right now.
Use the commands:
$ git checkout Dev
$ git pull

Then

$ bundle install
$ bundle exec puma

I've added the appserver called puma to the Gemfile so when your working
on your local machine use the instruction above to run the application.

If you want to do the bundle install to a directory that is inside the app you can run
$ bundle install --path vendor/bundle
This will install the gems under the vendor/bundle directory. I am doing it this way right now
since I'm not using RVM . I have already added this directory to the .gitignore file also, so it won't be pulled into the github repo online.
